# Shared Project Settings
java_version=25

# Mod
mod_version=1.3.0
license=Read attached LICENSE.md

# Minecraft
minecraft_version=26.3

# Fabric
## https://fabricmc.net/develop
fabric_version=0.161.0+26.3
fabric_loader_version=0.19.5
loom_version=1.18-SNAPSHOT

# Dependencies
mixinextras_version=0.5.5
sable_companion_version=1.6.0
forgeconfigapiport_version=26.3.1
energy_version=5.0.0

# Create-Fly：GitHub 仓库 LyXith/create-fly-fly 的 JitPack ref（tag / 分支）
create_fly_version=pack-26.3-latest

# Fabric metadata dependency versions
create_mod_version=6.0.9-1
sable_mod_version=26.3-3.0.0
sable_mod_version_range=>=2.0.0 <3.0.0
jei_version=31.6.0.25

# Mod Integration
computercraft_tweaked_version=1.120.3
natures_compass_version=26.3-2.5.1-fabric
explorers_compass_version=26.3-2.5.2-fabric
sodium_version=mc26.3-0.9.3-alpha.1-fabric
sodium_mod_version=0.9.3-alpha.1
iris_version=1.11.6+26.3
entityculling_version=CFBkR8Vm
scalablelux_version=0.1.6+fabric.c25518a

# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
